apiVersion: skaffold/v2beta5
kind: Config
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: test-plugin
      docker:
        dockerfile: Dockerfile
        target: kms-server
