apiVersion: v1
kind: Pod

metadata:
  name: test-plugin
  labels:
    app.kubernetes.io/name: test-plugin
spec:
  volumes:
    - name: certstore
      emptyDir: {}
    - name: ca
      hostPath:
        path: /etc/
    - name: socket
      hostPath:
        path: /var/lib/minikube/certs
      #      emptyDir: {}
    - name: logs
      emptyDir: {}
  containers:
    - name: plugin-server
      image: "test-plugin"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /certs/
          name: certstore
        - mountPath: /var/lib/minikube/certs
          name: socket
#        - mountPath: /var/log
#          name: logs
      env:
        - name: P11_LIB
          value: /usr/lib/softhsm/libsofthsm2.so
        - name: P11_TOKEN
          value: default
        - name: P11_PIN
          value: changeme
